apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapi-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-depl
  targetCPUUtilizationPercentage: 50
