apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-depl
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: aldosan33/shoppingapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
            - name: DatabaseSettings__DatabaseName
              value: CatalogDb
            - name: DatabaseSettings__CollectionName
              value: Products
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
