apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-depl
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: aldosan33/shoppingclient:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingapi-configmap
                  key: shoppingapi_url
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
