apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-srv
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 80
      nodePort: 31000
