apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-srv
spec:
  type: NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000
