version: "3.4"

services:
  shopping-api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    container_name: shoppingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "DatabaseSettings:ConnectionString=mongodb://shoppingdb:27017"
      - "DatabaseSettings:DatabaseName=CatalogDb"
      - "DatabaseSettings:CollectionName=Products"
    depends_on:
      - shopping-db
    ports:
      - "8000:80"

  shopping-client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile
    container_name: shoppingclient
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ShoppingAPIUrl=http://shoppingapi"
    depends_on:
      - shopping-db
      - shopping-api
    ports:
      - "8001:80"

  shopping-db:
    image: mongo
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
